# Test your FastAPI endpoints

POST http://localhost:8000/login
Content-Type: application/json

{
  "username": "admin",
  "password": "1234"
}

###
POST http://localhost:8000/graphql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTc0OTE2MDkyOH0.ngGEHEAsjRJeMmXRDZXezrNST1xz59TdSOQGSKXa3Vo

{
  "query": " query{ users{id} }"
}
